### ISSUE TITLE
ANTLR version mismatch

### ISSUE THREAD

**Issue by erikeelde** [premex-ab/ownership-gradle-plugin#16]
> Task :validateOwnership FAILED
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.5.3ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.5.3

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.tomlj.internal.TomlLexer
        at org.tomlj.Parser.parse(Parser.java:32)
        at org.tomlj.Toml.parse(Toml.java:56)
        at org.tomlj.Toml.parse(Toml.java:44)
        at se.premex.ValidateOwnershipTask.validationTask(ValidateOwnershipTask.kt:47)

**Comment by erikeelde** [comment]
Probably two separate issues - first seems to be merely a warning. Second is that tomlj isn't available on the plugin classpath.

**Comment by warting** [comment]
@erikeelde can you test with latest release and see if this is still an issue?
